# Generated by Django 4.0.5 on 2022-06-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('apellido', models.CharField(max_length=70, null=True)),
                ('edad', models.IntegerField(null=True)),
            ],
        ),
    ]
